### ISSUE TITLE
Issue with TF provider plugins that are downloaded by TF during "terraform init"

### ISSUE THREAD

**Issue by Obeltel** [ocp-power-automation/ocp4-upi-powervm#125]
Hello Team,

Please review following changes in TF version, might need minor correction:

https://github.com/ocp-power-automation/ocp4-upi-powervm/blob/8cbd966ee74057fa3bfc5bd780bbf72183f6b523/modules/4_nodes/versions.tf#L28

For TF ~> 0.13.0 , openstack provider should be change to:
```
source = "terraform-provider-openstack/openstack"
```

In regards to Third-party providers, e.g. [community-terraform-provider releases page](https://github.com/community-terraform-providers/terraform-provider-ignition/releases/tag/v2.1.0) , code should be also changed here, as not working as described on [ReadMe](https://github.com/ocp-power-automation/ocp4-upi-powervm#terraform-providers):
https://github.com/ocp-power-automation/ocp4-upi-powervm/blob/8cbd966ee74057fa3bfc5bd780bbf72183f6b523/modules/4_nodes/versions.tf#L24
Correct path to Third-party providers require a version as follow:
`.terraform/plugins/registry.terraform.io/terraform-providers/ignition/2.1/linux_amd64/terraform-provider-ignition_v2.1.0`

If we use official `terraform-providers/ignition v1.2.1` several errors are reported during "terraform apply":
```
Error: Missing required argument

  on modules/4_nodes/nodes.tf line 34, in data "ignition_file" "b_hostname":
  34: data "ignition_file" "b_hostname" {

The argument "filesystem" is required, but no definition was found.


Error: Unsupported argument
on modules/4_nodes/nodes.tf line 35, in data "ignition_file" "b_hostname":
  35:     overwrite   = true

An argument named "overwrite" is not expected here.

Errors On following lines as well: 95, 97, 149, 151
```

Openstack provider should be changed to `source = "terraform-provider-openstack/openstack"` on following TF files, as well:
https://github.com/ocp-power-automation/ocp4-upi-powervm/blob/8cbd966ee74057fa3bfc5bd780bbf72183f6b523/modules/1_bastion/versions.tf#L28

https://github.com/ocp-power-automation/ocp4-upi-powervm/blob/8cbd966ee74057fa3bfc5bd780bbf72183f6b523/modules/2_network/versions.tf#L24

Thank you!

**Comment by yussufsh** [comment]
Thank you for reporting this.

I agree with OpenStack provider plugin change, they have renamed their namespace recently. We will update that as soon as possible.

On `terraform-providers/ignition` we are forced to use specific version as per the latest RHCOS ignition spec (v3.1.0). For OCP 4.5, we have to use `release-4.5` branch of this repo which require ignition provider version v1.2 with Terraform 0.12. For OCP >= 4.6 (pre-releases) onward we will have to use the master branch (should have a dedicated branch soon) with ignition provider version v2.1 and Terraform 0.13.

Unfortunately v3.1.0 ignition spec support is not part of community provider terraform-providers/ignition and updates for it are in the forked repo which we are requesting users to download and setup manually.
