### ISSUE TITLE
Required fields not set for nodes.ft (using master and TF13)

### ISSUE THREAD

**Issue by cunlifs** [ocp-power-automation/ocp4-upi-powervm#131]
When trying to deploy v4.6 using master branch and TF13, nodes.tf fails.

Output from apply:
module.bastion.data.openstack_compute_flavor_v2.bastion: Refreshing state...
module.network.data.openstack_networking_network_v2.network: Refreshing state...
module.network.data.openstack_networking_subnet_v2.subnet: Refreshing state...

Error: "vcpus": required field is not set
  on modules/4_nodes/nodes.tf line 46, in resource "openstack_compute_flavor_v2" "bootstrap_scg":
  46: resource "openstack_compute_flavor_v2" "bootstrap_scg" {

Error: "ram": required field is not set
  on modules/4_nodes/nodes.tf line 46, in resource "openstack_compute_flavor_v2" "bootstrap_scg":
  46: resource "openstack_compute_flavor_v2" "bootstrap_scg" {

Error: "disk": required field is not set
  on modules/4_nodes/nodes.tf line 46, in resource "openstack_compute_flavor_v2" "bootstrap_scg":
  46: resource "openstack_compute_flavor_v2" "bootstrap_scg" {

Error: "ram": required field is not set
  on modules/4_nodes/nodes.tf line 109, in resource "openstack_compute_flavor_v2" "master_scg":
 109: resource "openstack_compute_flavor_v2" "master_scg" {

Error: "disk": required field is not set
  on modules/4_nodes/nodes.tf line 109, in resource "openstack_compute_flavor_v2" "master_scg":
 109: resource "openstack_compute_flavor_v2" "master_scg" {

Error: "vcpus": required field is not set
  on modules/4_nodes/nodes.tf line 109, in resource "openstack_compute_flavor_v2" "master_scg":
 109: resource "openstack_compute_flavor_v2" "master_scg" {

Error: "vcpus": required field is not set
  on modules/4_nodes/nodes.tf line 164, in resource "openstack_compute_flavor_v2" "worker_scg":
 164: resource "openstack_compute_flavor_v2" "worker_scg" {

Error: "ram": required field is not set
  on modules/4_nodes/nodes.tf line 164, in resource "openstack_compute_flavor_v2" "worker_scg":
 164: resource "openstack_compute_flavor_v2" "worker_scg" {

Error: "disk": required field is not set
  on modules/4_nodes/nodes.tf line 164, in resource "openstack_compute_flavor_v2" "worker_scg":
 164: resource "openstack_compute_flavor_v2" "worker_scg" {

-------------
Removing line 112 from ocp.tf
module "nodes" {
    depends_on                      = [module.helpernode]        <------------- line 112 
    source                          = "./modules/4_nodes"

Allows the apply to run. 

Although the first run fails with:
![image](https://user-images.githubusercontent.com/15692452/97550085-1e282380-19c9-11eb-9b59-135f136590d3.png)

You can re-run and cluster installs.

**Comment by yussufsh** [comment]
@cunlifs I have reported this to Terraform community at https://github.com/hashicorp/terraform/issues/26749

**Comment by yussufsh** [comment]
So we did not get much support from Terraform community in fixing the actual module dependency problem. With @pravin-dsilva  also facing same issue I went ahead to provide alternative approach to fix the issue.

Once module dependency is removed from nodes block the data sources read the flavor information.
