### ISSUE TITLE
Deployments with fixed_ip_v4 for bastion can lead to port reservation conflicts

### ISSUE THREAD

**Issue by torwen1** [ocp-power-automation/ocp4-upi-powervm#182]
Hello team,

Using the fixed_ip_v4 can lead to port reservation conflicts with bootstrap, masters, or workers.

In PowerVC you will see something like attached in the picture.

The reason for this is, that the network module can run before the bastion module and so it can pick the "reserved" IP adress from the var.tfvars.

I solved it by changed in the ocp.tf file and added some dependencies for the network module, to ensure that it isn't running before bastion has finished. I also ensured that the node module is not started before the network module.

My dependencies in the ocp.tf are looking like this now:
module "network" {
     source = "./modules/2_network"
     depends_on = [module.bastion]
<SNIP>

module "nodes" {
    source = "./module/4_nodes"
    depends_on = [module.network]
<SNIP>

module "install" {
    source = "./module/5_install"
    depends_on = [module.helpernode, module.node]
<img width="1540" alt="Screenshot 2021-03-12 at 08 47 43" src="https://user-images.githubusercontent.com/66682160/110909131-04500300-8310-11eb-9616-7e2617ff9c16.png">

**Comment by yussufsh** [comment]
Thanks for trying out this new feature.

The solution you provided is good but I don't want to go that path of module dependency as it has unknown impact on other data sources we use. We had a bug with SCG when I had removed the module dependency from the helpernode module. We can still use variable dependency which work well IMO.

The fix I am proposing is to use network port for bastion reserved IP. This way we can manage the dependency within network module.

**Comment by torwen1** [comment]
Thanks for your response. If you already made the experience, that having module dependencies can create some other trouble, then it makes sense to have a different approach.

**Comment by yussufsh** [comment]
I have used variable dependency instead of module dependency to fix this issue. PR https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188 is created where the network port of cluster nodes will be created only when bastion is ready.

This will ensure we don't utilize the network resources until bastion is running and already setup.
