### ISSUE TITLE
Add support for PowerVC 2.0

### ISSUE THREAD

**Issue by bpradipt** [ocp-power-automation/ocp4-upi-powervm#189]

**Comment by dannert** [comment]
It "mostly" works with PvC 2.0, only issue is that storage provider in PvC 2.0 is version 3, whereas in PvC 1.x it is version 2 and that is what is coded in the playbooks in the context of the NFS storage for Bastion.

**Comment by yussufsh** [comment]
If PowerVC 1.X also support v3 cinder APIs then we should upgrade the code that will work on both 1.X and 2.X. What say @bpradipt ? May need confirmation from PowerVC folks on the API support.

**Comment by dannert** [comment]
I believe PvC 1.X only supports version 2.

**Comment by yussufsh** [comment]
I have cinderv3 on our PowerVC setup...
```
Version: 1.4.4.1
Build: 20200417-0238
```

```
# openstack catalog list | grep cinder
| cinder    | volume       | RegionOne                                                                                            |
| cinderv3  | volumev3     | RegionOne                                                                                            |
| cinderv2  | volumev2     | RegionOne
```

**Comment by bpradipt** [comment]
@sudeeshjohn did you happen to try with pvc 2.0 in your setup ?

**Comment by sudeeshjohn** [comment]
@bpradipt Yes, I have tried ocp4.8 deployment on PowerVC 2.0.1 with Novalink host. The deployment was successful.

**Comment by schabrolles** [comment]
Hi, It almost works on powervc 2.0.1 with OCP 4.7 except for additional nfs volume on the bastion. (as said previously by @dannert)

```
Error: Error creating openstack_blockstorage_volume_v2: Resource not found

  on modules/1_bastion/bastion.tf line 287, in resource "openstack_blockstorage_volume_v2" "storage_volume":
 287: resource "openstack_blockstorage_volume_v2" "storage_volume" {
``` 

Do you know how this can be fixed?

**Comment by yussufsh** [comment]
We can either upgrade to use cinder v3 APIs via Terraform OR host separate branches for PowerVC 1.X and 2.X (not recommended).

Assuming we have a way to install cinder v3 on PowerVC 1.X as shown in https://github.com/ocp-power-automation/ocp4-upi-powervm/issues/189#issuecomment-867334080, we can put this as a hard requirement.

**Comment by schabrolles** [comment]
@yussufsh, Having a variable in TF like `powerVC_2=true` could be used to force cinder_v3.
What do you think?

**Comment by yussufsh** [comment]
That is actually a good idea 👍

**Comment by dannert** [comment]
I'm trying to install OCP 4.8 with PvC 2.0.2.1 and this issue still exists. PvC 2.0.2.1 api only shows Cinder v3 and not V2 support.

The workaround I'm using is to modify modules/bastion/bastion.tf:
old: 
resource "openstack_blockstorage_volume_v2" "storage_volume" {
    count       = var.storage_type == "nfs" ? 1 : 0

    name        = "${var.cluster_id}-${var.storage_type}-storage-vol"
    size        = var.volume_size
    volume_type = var.volume_storage_template
}

resource "openstack_compute_volume_attach_v2" "storage_v_attach" {
    depends_on      = [null_resource.bastion_init]
    count       = var.storage_type == "nfs" ? 1 : 0

    volume_id   = openstack_blockstorage_volume_v2.storage_volume[count.index].id
    instance_id = openstack_compute_instance_v2.bastion[count.index].id
}	
**NEW:**
resource "openstack_blockstorage_volume_**v3**" "storage_volume" {
    count       = var.storage_type == "nfs" ? 1 : 0

    name        = "${var.cluster_id}-${var.storage_type}-storage-vol"
    size        = var.volume_size
    volume_type = var.volume_storage_template
}

resource "openstack_compute_volume_attach_v2" "storage_v_attach" {
    depends_on      = [null_resource.bastion_init]
    count       = var.storage_type == "nfs" ? 1 : 0

    volume_id   = openstack_blockstorage_volume_**v3**.storage_volume[count.index].id
    instance_id = openstack_compute_instance_v2.bastion[count.index].id
}

**Comment by sdelabarre** [comment]
PowerVC 1.4 went out of support 2022-04-30. Shouldn't we consider moving to cinder V3 ?
https://www.ibm.com/support/pages/lifecycle/search?q=5765-VCS
