### ISSUE TITLE
Use external LB and DNS for install

### ISSUE THREAD

**Issue by bpradipt** [ocp-power-automation/ocp4-upi-powervm#191]
We should have a way to disable haproxy and DNS in bastion when using external LB and DNS services.

**Comment by cs-zhang** [comment]
Tested to use predefined DNS and load balancer on a different host, the installation completed and works fine. Here are the manual steps:

1.   on ather host to config DNS and haproxy with predefined IP and hostname, note for DNS config, need to use load balancer IP for api, api-int and *.apps.
2.  run ocp4-helpernode to config the bastion as normal
3.  update /etc/dhcp/dhcpd.conf, using external DNS IP for domain-name-servers
4.  restart dhcpd
5.  stop DNS and haproxy (optinal, not required)
6.  run ocp4-playbooks to install OCP

 There are two tasks need to be done to implement it:

1.  Enable ocp4-upi-powervm to support predefined IP for all cluster nodes ( bastion, bootstrap, masters and workers)
2. Enable the ocp4-helpernode to support to use external DNS for DHCP config

**Comment by cs-zhang** [comment]
PR created for ocp4-helpernode: https://github.com/RedHatOfficial/ocp4-helpernode/pull/219
