### ISSUE TITLE
Assign pre-existent IP to bastion - fixed_ips doesn't work

### ISSUE THREAD

**Issue by maniasso** [ocp-power-automation/ocp4-upi-powervm#208]
I've noticed that is only possible to assign the bastion_vip which is used for keepalived when 2 HA bastion servers are set.
the fixed_ips is ignored at bastion, only fixed_ip_v4 which is used by bastion_vip and keepalived is used, is possible to add the possibility to assign a pre-defined IP to bastions when use HA?

**Comment by yussufsh** [comment]
@cs-zhang

**Comment by maniasso** [comment]
An issue I see when assign pre-existent IPs to masters, bootstrap and workers, there's a risk to bastion gets the IP that should be reserverd to OCP cluster and builds stop since IP is already in use, so a good practice would be have the possibility to determine the IP the bastion(s) will have as well.

**Comment by cs-zhang** [comment]
That is caused by the static IP is not support the bastion HA,  I'll add it.  In this case, all VMs created by TF need to use static IP, or not use it at all.
