### ISSUE TITLE
Implement data disk capability on worker nodes for OCS

### ISSUE THREAD

**Issue by lukebrowning** [ocp-power-automation/ocp4-upi-powervm#210]
This capability is implemented in ocp4-upi-powervs and ideally the same api would be provided in both cases.

This is needed in general for customer workloads as well.

**Comment by bpradipt** [comment]
Thanks @lukebrowning for raising the enhancement request

**Comment by yussufsh** [comment]
@bpradipt I am suspecting we may face https://github.com/ocp-power-automation/ocp4-upi-powervm/issues/192 again with rhcos nodes.

**Comment by lukebrowning** [comment]
@bpradipt PR #212 resolves this issue for ocp 4.8.   Can it be back ported to ocp 4.7 and 4.6 release branches?    I believe CP4D is based on OCP 4.6.

**Comment by lukebrowning** [comment]
Disk add failed --

[root@rdr-lbr48-5dba-bastion-0 ~]# for i in worker-0 worker-1 worker-2; do echo $i; ssh core@$i sudo lsblk -a | grep 768;  done; 
worker-0
sdb      8:16   0   768G  0 disk 
sdd      8:48   0   768G  0 disk 
sdf      8:80   0   768G  0 disk 
sdh      8:112  0   768G  0 disk 
worker-1
sdb      8:16   0   768G  0 disk 
sdd      8:48   0   768G  0 disk 
worker-2
sdb      8:16   0   768G  0 disk 
sdd      8:48   0   768G  0 disk 
sdf      8:80   0   768G  0 disk 
sdh      8:112  0   768G  0 disk 

We are expecting each disk to have four paths - mount points.

@cs-zhang @bpradipt

**Comment by lukebrowning** [comment]
@aishwaryabk @yussufsh Disk attached failed

**Comment by aishwaryabk** [comment]
@lukebrowning Could you please provide details of the configurations of master and worker nodes?

**Comment by lukebrowning** [comment]
bastion        = {instance_type = "medium", image_id = "ea8886ed-32f6-4f6c-82b8-c49c5867795d", "count" = 1}
bootstrap      = {instance_type = "large", image_id = "09e18a43-8440-40f2-abe6-b8824fb679cd", "count" = 0}
master         = {instance_type = "large", image_id = "09e18a43-8440-40f2-abe6-b8824fb679cd", "count" = 3}
worker         = {instance_type = "xlarge", image_id = "09e18a43-8440-40f2-abe6-b8824fb679cd", "count" = 3, data_volume_count = 1, data_volume_size = 768}

**Comment by lukebrowning** [comment]
[terraform-show.log](https://github.com/ocp-power-automation/ocp4-upi-powervm/files/6791544/terraform-show.log)

**Comment by lukebrowning** [comment]
rhcos-48.84.202105130819-0-openstack.ppc64le on https://scnlpowercloud.pok.stglabs.ibm.com/powervc/index.html#t=images.image_details&imageId=09e18a43-8440-40f2-abe6-b8824fb679cd

**Comment by lukebrowning** [comment]
Examining dmesg from each of the worker nodes, there are a couple of missing dmesg statements on the broken worker node.  The missing statements come from ostree-prepare-root.   

```
[    7.476231] systemd[1]: Mounted /sysroot.
[    7.478797] systemd[1]: Starting OSTree Prepare OS/...
[    7.579795] ostree-prepare-root[1914]: Resolved OSTree target to: /sysroot/ostree/deploy/rhcos/deploy/d997e956e984e92109a9b4df1795669023bddf32e778e8132c429c2ff74bf654.1
[    7.580245] ostree-prepare-root[1914]: sysroot configured read-only: 1, currently writable: 1
[    7.591770] systemd[1]: sysroot-ostree-deploy-rhcos-deploy-d997e956e984e92109a9b4df1795669023bddf32e778e8132c429c2ff74bf654.1-etc.mount: Succeeded.
[    7.591814] systemd[1]: sysroot-ostree-deploy-rhcos-deploy-d997e956e984e92109a9b4df1795669023bddf32e778e8132c429c2ff74bf654.1.mount: Succeeded.
----------------------------------------- Missing on broken node -------------------------------------
[    7.595902] systemd[1]: sysroot.tmp-usr.mount: Succeeded.
[    7.595939] systemd[1]: sysroot.tmp-etc.mount: Succeeded.
[    7.595973] systemd[1]: sysroot.tmp.mount: Succeeded.**
-----------------------------------------------------------------------------------------------------------------
[    7.596468] systemd[1]: Started OSTree Prepare OS/.
[    7.597094] systemd[1]: Reached target Subsequent (Not Ignition) boot complete.
[    7.597347] systemd[1]: Reached target Initrd Root File System.
[    7.600348] systemd[1]: Starting Reload Configuration from the Real Root...
```

**Comment by lukebrowning** [comment]
Does anybody know about ostree?

**Comment by lukebrowning** [comment]
@manojnkumar @gitsridhar fyi -- This is rhcos 4.8 rc3

**Comment by aishwaryabk** [comment]
> bastion = {instance_type = "medium", image_id = "ea8886ed-32f6-4f6c-82b8-c49c5867795d", "count" = 1}
> bootstrap = {instance_type = "large", image_id = "09e18a43-8440-40f2-abe6-b8824fb679cd", "count" = 0}
> master = {instance_type = "large", image_id = "09e18a43-8440-40f2-abe6-b8824fb679cd", "count" = 3}
> worker = {instance_type = "xlarge", image_id = "09e18a43-8440-40f2-abe6-b8824fb679cd", "count" = 3, data_volume_count = 1, data_volume_size = 768}

	[root@aish-48-bastion-0 ~]# for i in worker-0 worker-1 worker-2; do echo $i; ssh core@$i sudo lsblk -a | grep 20; done;
	worker-0
	sda      8:0    0   120G  0 disk
	sdb      8:16   0    20G  0 disk
	sdc      8:32   0   120G  0 disk
	sdd      8:48   0    20G  0 disk
	worker-1
	sda      8:0    0   120G  0 disk
	sdb      8:16   0    20G  0 disk
	sdc      8:32   0   120G  0 disk
	sdd      8:48   0    20G  0 disk
	worker-2
	sda      8:0    0   120G  0 disk
	sdb      8:16   0    20G  0 disk
	sdc      8:32   0   120G  0 disk
	sdd      8:48   0    20G  0 disk
	
Using master ={count = 3} and worker = {count = 3, data_volume_count = 1, data_volume_size = 20} 
The disks are getting attached to the worker nodes.

**Comment by lukebrowning** [comment]
@aishwaryabk Your test created two 20 GB disks per worker.   Mine created four on two nodes and two on the other.   Could this be caused by the use of different host FC adapters?   Is there one device per FC port?   Which host group did you use?   I used p8_pvm.    Which host servers were allocated in your cluster for worker nodes?

**Comment by lukebrowning** [comment]
In my failing case, worker-2, the one with two disks, has Tuleta in the host name.  The other two nodes are hosted by a server that does not include Tuleta in the name.  They have 4 disks each.

**Comment by aishwaryabk** [comment]
@lukebrowning It could be caused by the use of multiple hosts for the cluster. The number of FC ports connected to the storage is different across hosts.
I have used Jupiter environment and "p8" host group. All nodes are hosted on Tuleta.

**Comment by lukebrowning** [comment]
This appears to be a powervc host group definition that is inconsistent with ocs-ci.   I am not sure it is an ocs issue.   We use ocs-ci to deploy ocs which checks how many disks are detected per node.  

@gitsridhar Please test OCP UI installs of OCS on powervc.
