### ISSUE TITLE
Ability to add custom RHCOS kernel option

### ISSUE THREAD

**Issue by bpradipt** [ocp-power-automation/ocp4-upi-powervm#27]
Sometimes there is a need to add specific kernel option based on requirement. For example adding `slub_max_order=0` to evaluate the memory footprint impact for containers.

This issue is to discuss and come up with such a mechanism

**Comment by bpradipt** [comment]
There are two phases when such settings will be needed:
1. Before start of OCP install
2. Post OCP install

For post OCP install, the settings can be performed via machineconfig operator and we can create an ansible playbook for the same. This is tracked here - https://github.com/ocp-power-automation/ocp4-playbooks/issues/2
For pre OCP install this either needs to be handled as part of this project or the helper node playbook

**Comment by bpradipt** [comment]
Post OCP install config is addressed by the following PR - https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/36

**Comment by bpradipt** [comment]
For pre-install (day-1) also machine config can be used as described here - https://docs.openshift.com/container-platform/4.3/installing/install_config/installing-customizing.html#installation-special-config-kargs_installing-customizing

@yussufsh @Prajyot-Parab

**Comment by torwen1** [comment]
@yussufsh @Prajyot-Parab @bpradipt 
If I see it correct, then this issue can be closed?! I have used the option in the some weeks ago and it was working like I expected it.

**Comment by bpradipt** [comment]
Yeah.. Thanks @torwen1
