### ISSUE TITLE
Set baremetal flag to false explicitly in helpernode vars file template

### ISSUE THREAD

**Issue by Prajyot-Parab** [ocp-power-automation/ocp4-upi-powervm#273]
**What is happening?**
The default value of `baremetal` flag is set to  `true` in helpernode playbook repo. This is running certain unecessary tasks, which are not required on `powervm` platform.

**Possible solution:**
Set the `baremetal` flag to `false` explicitly while generating the helpernode vars file template to fix it.

**Comment by yussufsh** [comment]
This is true for [ocp4-upi-powervs](https://github.com/ocp-power-automation/ocp4-upi-powervs) as well right?

**Comment by Prajyot-Parab** [comment]
> This is true for [ocp4-upi-powervs](https://github.com/ocp-power-automation/ocp4-upi-powervs) as well right?

Yes, once we have an update from QE team, will raise PR there as well. (will log a issue there for now)
