### ISSUE TITLE
Request adding support for proxy environments

### ISSUE THREAD

**Issue by torwen1** [ocp-power-automation/ocp4-upi-powervm#29]
A lot of companies have limited access from their environments to the internet. Most of them are using web proxies to allow controlled access from systems.

It would help a lot to have such support in your automation.
Setting a proxy would be needed for:
- yum (yum.conf)
- RHSM (rhsm.conf)
- openshift-installer config file 
- bastion server environment variables (in RHEL 8 it is done by the file /etc/profile.d/http_proxy.sh )
- git command

Important is also the no_proxy and that the domain used by the user gets added. Otherwise the installation procedure might get stuck at a point where it shouldn't go through a proxy, but because of the missing no_proxy entry it does.

**Comment by bpradipt** [comment]
Thanks a lot for raising the feature request @torwen1 . We'll take a look into the feature request and get back
