### ISSUE TITLE
Request adding support for alternatives to git clones

### ISSUE THREAD

**Issue by torwen1** [ocp-power-automation/ocp4-upi-powervm#30]
Beside my proxy support request, there are also companies where the systems getting a mirror registry for OpenShift, but still don't have access to the internet.

In such cases it would be great to have the option to define a alternative for the two git clones you are using in your toolset, like pulling a tar.gz from a web server within the local network instead.

**Comment by bpradipt** [comment]
Thanks for raising this issue. We'll take a look at this and explore how to incorporate the functionality.

**Comment by yussufsh** [comment]
Alternate repos are done via https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/94.

TODO: Provide option for local or http hosted archive file (zip/tar/gz)

**Comment by bpradipt** [comment]
We'll use this issue for further work on this one - https://github.com/ocp-power-automation/ocp4-upi-powervm/issues/89
