### ISSUE TITLE
Verify running the TF automation from Power Linux system

### ISSUE THREAD

**Issue by bpradipt** [ocp-power-automation/ocp4-upi-powervm#33]
TF binary for Power is available from the following link - https://www.power-devops.com/terraform
This issue is to track the verification of TF automation from Power Linux system

**Comment by yussufsh** [comment]
I have tried this with the kvm automation we have which works well.. Will try on powervm as well.

We will also need to build and provide the terraform plugins for the providers we use as shown below. Users can also build them on their power machines using Golang.

```
ocp4-upi-powervm# terraform version
Terraform v0.12.20
+ provider.ignition v1.2.1
+ provider.null v2.1.2
+ provider.openstack v1.28.0
+ provider.random v2.2.1

```

**Comment by bpradipt** [comment]
How about asking the owner of  https://www.power-devops.com/terraform and check if it can be made available via the same site ?

**Comment by yussufsh** [comment]
@rpsene had someone work on unicamp he had mentioned. He may have more information on the above site as well.

**Comment by yussufsh** [comment]
We could also make a doc explaining how to install the provider plugins using `go get -u github.com/X/Y` on Power systems.

**Comment by sihvotom** [comment]
Hello!

I am struggling with the same issue; my DevOps infra is built on top of PowerVM (where also our production env resides)

 I am able to compile TF on PowerVM..but having the needed providers compiled with correct version; and added to Terraform configuration (e.g telling TF to look for local provider binaries instead of url) gives maximal headache... So if there would be "ready made" full package (or instructions how to get working combination)  for PowerVM, it would be highly appreciated.

**Comment by yussufsh** [comment]
> I am able to compile TF on PowerVM..but having the needed providers compiled with correct version; and added to Terraform configuration (e.g telling TF to look for local provider binaries instead of url) gives maximal headache... So if there would be "ready made" full package (or instructions how to get working combination) for PowerVM, it would be highly appreciated.

Hi @sihvotom 
We have a good documentation in our KVM project. Please check https://github.com/ocp-power-automation/ocp4-upi-kvm/blob/master/docs/terraform-provider-build.md#on-ibm-power-systems. You will need to compile all the Terraform plugins at the required version tag on Power.

**Comment by sihvotom** [comment]
Many Thanks for quick reply Yussuf! Will take a look on that; Br,tommi

**Comment by sihvotom** [comment]
go version
go version go1.14.10 linux/ppc64le

export PATH=$PATH:$GOPATH/bin
TF_DEV=1 scripts/build.sh
==> Removing old directory...
which: no gox in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/go/bin:/bin)
==> Installing gox...
==> Building...
scripts/build.sh: line 60: gox: command not found

==> Results:
total 0

So seems that I am missing gox dependency; how to fetch that conveniently on ppc64le? 
Br,
tommi

**Comment by yussufsh** [comment]
` go get -u github.com/mitchellh/gox`

**Comment by sihvotom** [comment]
One more stupid question; is the some exact dependency / compatibility between the terraform & the providers?
Compiling went now OK, but it says:
[root@terraform]# bin/terraform version
Terraform v0.13.2

Your version of Terraform is out of date! The latest version
is 0.13.4. You can update by downloading from https://www.terraform.io/downloads.html

So if I get now 0.13.4; should I still use VERSION=2.3.0 for terraform-provider-random for example, or get some newer version for that too?

**Comment by yussufsh** [comment]
> So if I get now 0.13.4; should I still use VERSION=2.3.0 for terraform-provider-random for example, or get some newer version for that too?

Those versions are specific to KVM project which should be similar (but not same for powervm/powervc). I will give you the versions list from my x86 terminal below.
Also, note that if you want to deploy the current stable release OCP 4.5.X then you need to move to `release-4.5` branch which needs Terraform v0.12.X. The local plugins directory also changes as per the Terraform version.

These are the versions I have for `master` branch for deploying OCP 4.6 on PowerVC.
```
terraform version
Terraform v0.13.4
+ provider registry.terraform.io/community-terraform-providers/ignition v2.1.1
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.32.0
```

These are the version I have for `release-4.5` branch for deploying OCP 4.5 on PowerVC.
```
# terraform_0.12.20 version
Terraform v0.12.20
+ provider.ignition v1.2.1
+ provider.null v2.1.2
+ provider.openstack v1.32.0
+ provider.random v2.3.0

Your version of Terraform is out of date! The latest version
is 0.13.4. You can update by downloading from https://www.terraform.io/downloads.html
```

**Comment by sihvotom** [comment]
Many Thanks Yussuf!

Br,
tommi

Ystävällisin terveisin / Best regards,

Tommi Sihvo, Lead Service Architect

[signature_730403030]

TietoEVRY, Compute Services

**Comment by yussufsh** [comment]
We have the openstack and other providers compiled and distributed at https://github.com/ocp-power-automation/terraform-providers-power.

The [README](https://github.com/ocp-power-automation/terraform-providers-power/blob/main/README.md) provides the steps to run the automation from a Power machine.

**Comment by bpradipt** [comment]
@yussufsh can you also add a reference to the main README ?

**Comment by sihvotom** [comment]
Hello!

So does this mean that we now have Terraform + providers ready built for Power? 😊

If yes => SUPER!! 😊 Many Thanks Yussuf & Pradipta!!

Br,
tommi

Ystävällisin terveisin / Best regards,

Tommi Sihvo, Lead Service Architect

[signature_657688383]

TietoEVRY, Compute Services

**Comment by bpradipt** [comment]
> So does this mean that we now have Terraform + providers ready built for Power? 😊

Yes :-)

**Comment by cs-zhang** [comment]
Added steps to install Terraform and providers for Power system in host prereqs doc.

**Comment by yussufsh** [comment]
We have power support now hence closing this issue.

**Comment by sihvotom** [comment]
Hi Yussuf, Pradipta;

Hopefully you are safe & healthy!

Quick question > Where can I see the matrix that which Terraform version (& providers) I need to use for which Openshift version? (mainly 4.6 or 4.7)

Thanks,

Br,
tommi

Ystävällisin terveisin / Best regards,

Tommi Sihvo, Lead Service Architect

[signature_220655240]

TietoEVRY, Compute Services

From: Yussuf Shaikh ***@***.***>
Reply to: ocp-power-automation/ocp4-upi-powervm ***@***.***>
Date: Tuesday 16. March 2021 at 17.25
To: ocp-power-automation/ocp4-upi-powervm ***@***.***>
Cc: Tommi Sihvo ***@***.***>, Mention ***@***.***>
Subject: Re: [ocp-power-automation/ocp4-upi-powervm] Verify running the TF automation from Power Linux system (#33)


Closed #33<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Focp-power-automation%2Focp4-upi-powervm%2Fissues%2F33&data=04%7C01%7CTommi.Sihvo%40tieto.com%7C859eae7c3f214e48629608d8e88fca55%7Ccbede638a3d9459f8f4e24ced73b4e5e%7C1%7C0%7C637515051556843414%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fIZK1hCyTPs6J%2BJ%2FhfDp4RhJYvraKiOJxHN7pvd04HI%3D&reserved=0>.

**Comment by yussufsh** [comment]
> 
> Hi Yussuf, Pradipta; Hopefully you are safe & healthy! Quick question > Where can I see the matrix that which Terraform version (& providers) I need to use for which Openshift version? (mainly 4.6 or 4.7)

Please look for Power environment steps at https://github.com/ocp-power-automation/ocp4-upi-powervm/blob/master/docs/automation_host_prereqs.md#terraform

**Comment by sihvotom** [comment]
Thanks! 😊

Br,
tommi

Ystävällisin terveisin / Best regards,

Tommi Sihvo, Lead Service Architect

[signature_389610526]

TietoEVRY, Compute Services

From: Yussuf Shaikh ***@***.***>
Reply to: ocp-power-automation/ocp4-upi-powervm ***@***.***>
Date: Tuesday 30. March 2021 at 12.30
To: ocp-power-automation/ocp4-upi-powervm ***@***.***>
Cc: Tommi Sihvo ***@***.***>, Mention ***@***.***>
Subject: Re: [ocp-power-automation/ocp4-upi-powervm] Verify running the TF automation from Power Linux system (#33)


Hi Yussuf, Pradipta; Hopefully you are safe & healthy! Quick question > Where can I see the matrix that which Terraform version (& providers) I need to use for which Openshift version? (mainly 4.6 or 4.7)

Please look for Power environment steps at https://github.com/ocp-power-automation/ocp4-upi-powervm/blob/master/docs/automation_host_prereqs.md#terraform<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Focp-power-automation%2Focp4-upi-powervm%2Fblob%2Fmaster%2Fdocs%2Fautomation_host_prereqs.md%23terraform&data=04%7C01%7CTommi.Sihvo%40tieto.com%7Cd74493997ced44154db608d8f35e726b%7Ccbede638a3d9459f8f4e24ced73b4e5e%7C1%7C0%7C637526934264708118%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AvoSgkQk5xmEfN96dzG%2F3dml0kzhIP%2FNoYrFXGTOvEo%3D&reserved=0>
