### ISSUE TITLE
Support for restricted network install

### ISSUE THREAD

**Issue by bpradipt** [ocp-power-automation/ocp4-upi-powervm#35]
The automation assumes that all the Power systems have public network access. This issue is to add support for scenarios where only the system running the automation have public network access and the OCP LPARs (bastion, master, workers) don't have public network access.

**Comment by cs-zhang** [comment]
The current ocp4-upi-powervm already supports the proxy setting on bastion and cluster, that can meet the scenarios of this request.

**Comment by bpradipt** [comment]
@cs-zhang we'll need to account of the situation where even proxy is not available. All installation will be using images in mirror registry that will be setup behind the firewall

**Comment by bpradipt** [comment]
Duplicate of this - https://github.com/ocp-power-automation/ocp4-upi-powervm/issues/89
