### ISSUE TITLE
Service network configurable and other issues

### ISSUE THREAD

**Issue by henkwaanders** [ocp-power-automation/ocp4-upi-powervm#61]
Various issues and improvements for the roll-out.
* make the service network configurable is key for some implementations as their network is in the 172.30.0.0/16 segment. Need updates in the ocp4-playbooks repo as well.

* make the URL of the helpernode and the ocp4-playbooks repositories configurable through the var.tfvars file. This make it more easy to point to your own git-repo for development purposes. Need updates in the ocp4-playbooks repo as well

* the recommended way to install ansible in RHEL 8 is from the Red Hat Ansible repo and not using pip.

* create a htpasswd file with an admin user on beforehand and configure authentication during install so that the 'kubeadmin' user is nog needed anymore. Need updates in ocp4-playbooks as well

**Comment by bpradipt** [comment]
Closing stale issue.
