### ISSUE TITLE
Chrony does not work in restricted network install and not in sync with bastion

### ISSUE THREAD

**Issue by yussufsh** [ocp-power-automation/ocp4-upi-powervm#75]
Two issues seen while testing chrony:
1. Bastion node is not using chrony. Since the creation of ign files and backbone services are running on bastion, we need to make bastion also use the same chrony servers as the OCP cluster nodes.
2. Currently chrony config allow to use external ntp servers. When the nodes don't have internet access it makes chrony useless.

Possible solution: Setup NTP controller on the bastion node and make other node use the controller instead of external NTP servers.

We also need to see if chronyd can used behind a proxy.

@schabrolles Can we please investigate on the above issues.

**Comment by bpradipt** [comment]
Can't the OCP nodes use the proxy server to access external ntp servers ?

**Comment by yussufsh** [comment]
AFAIK chrony don't use a proxy for internet access. As such we can setup a NTP controller anywhere where the machines have access and use it as a NTP server.

**Comment by schabrolles** [comment]
@yussufsh,

1. Agree, we need to ensure that bastion is using the same ntp configuration to have to be in sync with other node. (may be in ocp-helpernode project, or in ocp4-playbook in ocp-config inside chrony.yaml task)

2. The current configuration allows local NTP server. This is currently what I use. Just specifying IP in the server section.
```
chrony_config = true
chrony_config_servers = [ {server = "10.3.21.254", options = "iburst"} ]
```

**Comment by yussufsh** [comment]
So best scenario would be to:
1. Ensure time is current in bastion. May be using chrony.
2. Setup chrony to `allow` the use in given network subnet.
3. Remove variable `chrony_config_servers` for good. And use the server as `bastion_ip` with iburst.

Ref: https://docs.oracle.com/cd/E90981_01/E90982/html/chrony.html#ntp-config

**Comment by yussufsh** [comment]
>     3\. Remove variable `chrony_config_servers` for good. And use the server as `bastion_ip` with iburst.

Or may be use this variable to setup on bastion. Then use bastion_ip for other nodes (via the playbook).

**Comment by schabrolles** [comment]
I think we should keep the variable, as some would prefer to use their own NTP server (in our case, the main network firewall).

I think we have 3 different scenarios 

1- No chrony configuration
`chrony_config`: false

2- Use the bastion as NTP server for the Node
bastion can be synchronized afterward to an external NTP
`chrony_config`: true

In that case , we set `chrony_config_servers` default to use the bastion_ip

3- Use a ntp server for Nodes and bastion. could be internal NTP (switch, firewall ...) or internet
`chrony_config`: true
`chrony_config_servers`: [{ server: IP, options: iburst }] 

What do you think ?

**Comment by bpradipt** [comment]
> AFAIK chrony don't use a proxy for internet access. As such we can setup a NTP controller anywhere where the machines have access and use it as a NTP server.

You are right. Looks like chrony doesn't support proxy atleast from the available public docs

**Comment by yussufsh** [comment]
I would go with no. 2 and use chrony by default.

No harm there and will help remove the errors due to time sync problems we would face because of hmc/host time mismatch. It would work with restricted network install even better when only bastion has internet access.

@schabrolles _I forgot to thank you for the chrony PRs. Helped me fix an old DHCP issue on our PowerVC (due to time mismatch between hosts). Thank you!_

**Comment by schabrolles** [comment]
@yussufsh yrw, happy to hear it also help you ;)

Regarding the 3 scenario, I think you should consider all of them, but apply n°2 by default.
`chrony_config`: true

if `chrony_config_servers` is undefined, then it will trigger the setup of chrony as a master on the bastion (with allow network)
and `chrony_config_servers` will be set to use bastion_ip as ntp server for the node.

if `chrony_config_servers` is defined, then all the node and the bastion must sync with the same ntp server (infrastructure provided)

I think the last one is also interesting, as big installation usually remove bastion node after installation (use infra DNS, real Storage server, HW loadbalancer, ... so I guess infrastructure NTP ...)

**Comment by bpradipt** [comment]
> @yussufsh yrw, happy to hear it also help you ;)
> 
> Regarding the 3 scenario, I think you should consider all of them, but apply n°2 by default.
> `chrony_config`: true
> 
> if `chrony_config_servers` is undefined, then it will trigger the setup of chrony as a master on the bastion (with allow network)
> and `chrony_config_servers` will be set to use bastion_ip as ntp server for the node.
> 
> if `chrony_config_servers` is defined, then all the node and the bastion must sync with the same ntp server (infrastructure provided)
> 
> I think the last one is also interesting, as big installation usually remove bastion node after installation (use infra DNS, real Storage server, HW loadbalancer, ... so I guess infrastructure NTP ...)

Yeah, all three are valid scenarios. In few environments there could be internal ntp servers.  
We can default to chrony server being the bastion ip.

**Comment by schabrolles** [comment]
I'm currently working on it and try to simplify it.

`chrony_config`: true (default)
=> this will setup the bastion as chrony server
 - Install Chrony
 - Synchronize to the local clock if no server is specified (local stratum 10)
 - Open firewall port for NTP
 - Allow cluster network to connect
 - configure the node (masters, workers, bootstrap) to sync with bastion

if `chrony_config_servers` is used with external server to sync
=> This will do the exact same as above and : 
 - Add external ntp server to sync with the bastion (higher priority than local clock)
 - configure the client (masters, workers, bootstrap) to sync with external ntp server, and bastion (in this priority order)

feedback welcomed ...

**Comment by yussufsh** [comment]
> if `chrony_config_servers` is used with external server to sync
> => This will do the exact same as above and :
> 
>     * Add external ntp server to sync with the bastion (higher priority than local clock)
> 
>     * configure the client (masters, workers, bootstrap) to sync with external ntp server, and bastion (in this priority order)

Let's always use bastion as a controller. All nodes (masters, workers, bootstrap) to sync with bastion always. And we ensure bastion is always syncing with the default time server if not specified in `chrony_config_servers`.

Environments which remove bastion after the install should manually change the chrony configs in cluster nodes to point to their external server. Just like they would do to change the DNS server.

**Comment by yussufsh** [comment]
I have created https://github.com/ocp-power-automation/ocp4-playbooks/issues/38 to make changes at the playbook level.

Once the change is merged we need to update this repo to make `chrony_config_servers` very much optional and changes in the documentation.

**Comment by schabrolles** [comment]
> Let's always use bastion as a controller.

@yussufsh it is the case, when 
 - `chrony_config_servers` is not specified
    * the bastion synchronize its clock with internet servers (if reachable) and Internal HW clock (when no internet connection) 
    * Nodes synchronize their time to the bastion

 - `chrony_config_servers` is specified
    * the bastion synchronize its clock with ntp servers (from `chrony_config_servers`) and Internal HW clock (if not reachable) 
    * Nodes synchronize their time to the ntp servers (from `chrony_config_servers`) AND the bastion

here is the `chrony.conf` on the nodes:
```
server <NTP_server_IP> iburst
server <Bastion_IP> iburst
driftfile /var/lib/chrony/drift
makestep 1.0 3
rtcsync
logdir /var/log/chrony
```

**Comment by yussufsh** [comment]
I was wondering why is this open still? Then I realized the issue was not properly linked to the PR. :-)
