### ISSUE TITLE
DNS record on the bastion DNS server seems to be wrong

### ISSUE THREAD

**Issue by schabrolles** [ocp-power-automation/ocp4-upi-powervm#76]
During my testing, I found that DNS server was not setup properly.

my nodes are named: `<node_name>.<cluser_id>.<domain>.<cluster_id>.<domain>` instead of just `<node_name>.<cluser_id>.<domain>`

Here is the output of `helpernodecheck dns-masters`

```
======================
DNS Config for Workers
======================

; Create entries for the worker hosts
worker-0.ocp-450c.fit.com		IN	A	10.3.21.40
worker-1.ocp-450c.fit.com		IN	A	10.3.21.36
worker-2.ocp-450c.fit.com		IN	A	10.3.21.10
;

======================
DNS Lookup for Workers
======================

worker-0.ocp-450c.fit.com.ocp-450c.fit.com
-------------------------------------------------
IP: 10.3.21.40
Reverse: worker-0.ocp-450c.fit.com.ocp-450c.fit.com.

worker-1.ocp-450c.fit.com.ocp-450c.fit.com
-------------------------------------------------
IP: 10.3.21.36
Reverse: worker-1.ocp-450c.fit.com.ocp-450c.fit.com.

worker-2.ocp-450c.fit.com.ocp-450c.fit.com
-------------------------------------------------
IP: 10.3.21.10
Reverse: worker-2.ocp-450c.fit.com.ocp-450c.fit.com.
```

We should be able to solve this issue by using the **short hostname** in `helpernode_var.yaml` template file.

**Comment by yussufsh** [comment]
I already had the commit ready for this :-)
I will let you continue with some suggested changes.

**Comment by yussufsh** [comment]
Re-opening this as we also want to change the cluster node hostnames. The hostname was at par to the DNS entries.

See https://github.com/ocp-power-automation/ocp4-upi-kvm/pull/31/files for similar change.
