### ISSUE TITLE
Possibility to specify cluster_id without prefix

### ISSUE THREAD

**Issue by schabrolles** [ocp-power-automation/ocp4-upi-powervm#88]
The current implementation of **user-defined cluster_id** (https://github.com/ocp-power-automation/ocp4-upi-powervm/issues/68) looks a bit not totaly achieved to me (but it is maybe just for me...)

In all openshift documentation, `cluster_id` is a subdomain. 
API: api.<cluster_id>.<domain>  ex: api.mycluster.mydomain.org
applications: <app>.apps.<cluster_id>.<domain>  ex portal.apps.mycluster.mydomain.org

With the current implementation #69 you can't really specify your cluster_id ... it is still a concatenation of `cluster_id` , `cluster_prefix`.... (with a - in between).

I think it could be good to let the user been able to choose its cluster name (without "-") 

your thoughts?

**Comment by bpradipt** [comment]
@yussufsh @cs-zhang your thoughts on this please ..

**Comment by cs-zhang** [comment]
We can just use cluster_id if cluster_id_prefix is not defined, and do not add "-" in front of cluster_id.
