### ISSUE TITLE
CoreOS 4.3.18 OpenStack Image failing

### ISSUE THREAD

**Issue by cunlifs** [ocp-power-automation/ocp4-upi-powervm#9]
Hi, I've converted the rhcos-4.3.18-ppc64le-openstack.ppc64le.qcow2.gz image and created a PowerVC image from it. However when I try and build from it with, even with a simple ignition file, I get a 'dev-disk-by' timeout error.

![image](https://user-images.githubusercontent.com/15692452/81299850-c9859a80-906e-11ea-8237-84acfafd7564.png)

**Comment by bpradipt** [comment]
@cunlifs How the VM is getting IP? Is it via DHCP or static IP setting ?

**Comment by cunlifs** [comment]
@bpradipt Using PowerVC IP Pool. PowerVC is aware of the IP during boot phase.

**Comment by thuche** [comment]
Hi Stuart, 
PowerVC will provide the IP from the IP pool then the DHCP server on bastion will be configured with this fixed IP address in /etc/hdcp.conf
host worker-0 {
        hardware ethernet fa:16:3e:03:xx:xx;
        fixed-address 10.3.xx.xx;
        option host-name "worker-0.ocp43-e2d1.power.com";**
.
What is the disk size for the CoreOS image you created in PowerVC, I have created a 20GB disk and now I have problem to deploy container, I have an error message "The node was low on resource: ephemeral-storage."

**Comment by cunlifs** [comment]
Hi Thierry, yes the /etc/dhcp/dhcp.conf is configured, e.g.
host master-0 {
        hardware ethernet fa:16:3e:ee:76:2e;
        fixed-address 9.x.x.x;
        option host-name "master-0.cl2-8ed5.example.com";
}

But still no luck. I created it with a 120GB LUN as 20GB seem too small.

**Comment by bpradipt** [comment]
@cunlifs from the error you see, it's due to CoreOS LPAR not getting IP and failing. So that should be  be fixed in your environment to make progress

**Comment by bpradipt** [comment]
@cunlifs can we close this issue ?

**Comment by yussufsh** [comment]
Due to inactivity closing this issue. Please reopen if you are still facing the issue.
