### ISSUE TITLE
Procedure of ansible installation of bastion host is incorrect

### ISSUE THREAD

**Issue by torwen1** [ocp-power-automation/ocp4-upi-powervm#98]
Hello Team,

I found a problem with the procedure of how the TF scripts are installing ansible.
In the bastion.tf you are using the following procedure to install ansible:
    provisioner "remote-exec" {
        inline = [
            "pip3 install ansible -q"
        ]
    }

The correct and supported package has to be installed with the following procedure on RHEL (RHEL 8 example below):
[root@host ~]# subscription-manager repos --list |grep -i ansible
<SNIP>
Repo ID:   ansible-2.9-for-rhel-8-ppc64le-rpms
Repo Name: Red Hat Ansible Engine 2.9 for RHEL 8 ppc64le (RPMs)
Repo URL:  https://cdn.redhat.com/content/dist/layered/rhel8/ppc64le/ansible/2.9/os
Repo ID:   ansible-2.8-for-rhel-8-ppc64le-rpms
Repo Name: Red Hat Ansible Engine 2.8 for RHEL 8 ppc64le (RPMs)
Repo URL:  https://cdn.redhat.com/content/dist/layered/rhel8/ppc64le/ansible/2.8/os
Repo ID:   ansible-2-for-rhel-8-ppc64le-rpms
Repo Name: Red Hat Ansible Engine 2 for RHEL 8 ppc64le (RPMs)
Repo URL:  https://cdn.redhat.com/content/dist/layered/rhel8/ppc64le/ansible/2/os
[root@tw-ocp-mirrorreg ~]# subscription-manager repos --enable ansible-2-for-rhel-8-ppc64le-rpms
Repository 'ansible-2-for-rhel-8-ppc64le-rpms' is enabled for this system.
[root@tw-ocp-mirrorreg ~]# yum install ansible
Updating Subscription Management repositories.
Red Hat Ansible Engine 2 for RHEL 8 ppc64le (RPMs)                                                                                                420 kB/s | 1.2 MB     00:03    
Red Hat Enterprise Linux 8 for Power, little endian - BaseOS (RPMs)                                                                                18 kB/s | 4.1 kB     00:00    
Red Hat Enterprise Linux 8 for Power, little endian - AppStream (RPMs)                                                                             11 kB/s | 4.5 kB     00:00    
Dependencies resolved.
==================================================================================================================================================================================
 Package                                  Architecture                    Version                                 Repository                                                 Size
==================================================================================================================================================================================
Installing:
 ansible                                  noarch                          2.9.11-1.el8ae                          ansible-2-for-rhel-8-ppc64le-rpms                          17 M
Installing dependencies:
 sshpass                                  ppc64le                         1.06-3.el8ae                            ansible-2-for-rhel-8-ppc64le-rpms                          27 k
Installing weak dependencies:
 python3-jmespath                         noarch                          0.9.0-11.el8                            rhel-8-for-ppc64le-appstream-rpms                          45 k

Transaction Summary
==================================================================================================================================================================================
Install  3 Packages

Total download size: 17 M
Installed size: 96 M
Is this ok [y/N]: 

Regards

PS: Sorry for the large letters... not sure why it is showing it like this....

**Comment by bpradipt** [comment]
Good point @torwen1. We should switch to ansible install via rpm.
